//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Антиконтрафакт2._1
{
    using System;
    using System.Collections.Generic;

    public partial class Request : AntiKEntities1
    {
        public int request_id { get; set; }
        public string request_code { get; set; }
        public string phonenumber { get; set; }
        public string email { get; set; }
        public string request_text { get; set; }
        public string request_salepoint { get; set; }
        public string request_product { get; set; }
        public string request_status { get; set; }
    }
}
